default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_kaohon_app_development

test:
  <<: *default
  database: rails_kaohon_app_test

production:
  <<: *default
  database: rails_kaohon_app_production
  username: rails_kaohon_app
  password: <%= ENV['RAILS_KAOHON_APP_DATABASE_PASSWORD'] %>
